-- 📚 Base de Datos para Sistema de Gestión de Biblioteca

-- 1. Profiles (extensión de auth.users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    role TEXT CHECK (role IN ('admin', 'teacher', 'student')) DEFAULT 'student',
    codigo_identificacion TEXT UNIQUE,
    telefono TEXT,
    estado TEXT CHECK (estado IN ('activo', 'inactivo', 'suspendido')) DEFAULT 'activo',
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS para profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver su propio perfil" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Los admins pueden ver todos los perfiles" ON public.profiles
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- 2. Categorías
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    descripcion TEXT,
    color_hex TEXT DEFAULT '#3B82F6',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cualquiera puede ver categorías" ON public.categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Solo admins pueden modificar categorías" ON public.categories FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 3. Ubicaciones
CREATE TABLE public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_name TEXT NOT NULL,
    section TEXT,
    row TEXT,
    capacity INTEGER DEFAULT 100,
    current_occupancy INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cualquiera puede ver ubicaciones" ON public.locations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Solo admins pueden modificar ubicaciones" ON public.locations FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 4. Libros
CREATE TABLE public.books (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    titulo TEXT NOT NULL,
    autor TEXT NOT NULL,
    isbn TEXT,
    editorial TEXT,
    año_publicacion INTEGER,
    categoria_id BIGINT REFERENCES public.categories(id),
    ubicacion_id BIGINT REFERENCES public.locations(id),
    cantidad_total INTEGER DEFAULT 1 NOT NULL,
    cantidad_disponible INTEGER DEFAULT 1 NOT NULL,
    codigo_barras TEXT UNIQUE,
    imagen_portada_url TEXT,
    estado TEXT CHECK (estado IN ('disponible', 'prestado', 'dañado', 'perdido')) DEFAULT 'disponible',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cualquiera puede ver libros" ON public.books FOR SELECT TO authenticated USING (true);
CREATE POLICY "Solo admins pueden modificar libros" ON public.books FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 5. Préstamos
CREATE TABLE public.loans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    libro_id UUID REFERENCES public.books(id) NOT NULL,
    usuario_id UUID REFERENCES public.profiles(id) NOT NULL,
    fecha_prestamo TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    fecha_devolucion_estimada TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_devolucion_real TIMESTAMP WITH TIME ZONE,
    estado TEXT CHECK (estado IN ('active', 'returned', 'overdue')) DEFAULT 'active',
    renovaciones INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios ven sus propios préstamos" ON public.loans FOR SELECT USING (auth.uid() = usuario_id);
CREATE POLICY "Admins ven todos los préstamos" ON public.loans FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 6. Reservas
CREATE TABLE public.reservas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    libro_id UUID REFERENCES public.books(id) NOT NULL,
    usuario_id UUID REFERENCES public.profiles(id) NOT NULL,
    fecha_reserva TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    fecha_expiracion TIMESTAMP WITH TIME ZONE NOT NULL,
    estado TEXT CHECK (estado IN ('pendiente', 'completada', 'cancelada', 'expirada')) DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.reservas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios ven sus propias reservas" ON public.reservas FOR SELECT USING (auth.uid() = usuario_id);
CREATE POLICY "Admins ven todas las reservas" ON public.reservas FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 7. Multas
CREATE TABLE public.multas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    prestamo_id UUID REFERENCES public.loans(id),
    usuario_id UUID REFERENCES public.profiles(id) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    motivo TEXT,
    estado TEXT CHECK (estado IN ('pendiente', 'pagada', 'condonada')) DEFAULT 'pendiente',
    fecha_generacion TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    fecha_pago TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.multas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios ven sus propias multas" ON public.multas FOR SELECT USING (auth.uid() = usuario_id);
CREATE POLICY "Admins ven todas las multas" ON public.multas FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 8. Notificaciones
CREATE TABLE public.notificaciones (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario_id UUID REFERENCES public.profiles(id) NOT NULL,
    tipo TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    leida BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios ven sus notificaciones" ON public.notificaciones FOR ALL USING (auth.uid() = usuario_id);

-- 9. Configuracion del Sistema
CREATE TABLE public.configuracion_sistema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave TEXT UNIQUE NOT NULL,
    valor TEXT NOT NULL,
    tipo_dato TEXT DEFAULT 'string',
    descripcion TEXT
);

-- Insertar valores iniciales
INSERT INTO public.configuracion_sistema (clave, valor, tipo_dato, descripcion) VALUES
('dias_prestamo_estudiante', '7', 'number', 'Días de préstamo para estudiantes'),
('dias_prestamo_profesor', '14', 'number', 'Días de préstamo para profesores'),
('dias_prestamo_admin', '30', 'number', 'Días de préstamo para administradores'),
('limite_libros_por_usuario', '3', 'number', 'Límite máximo de libros por usuario'),
('max_renovaciones', '2', 'number', 'Máximo de renovaciones permitidas'),
('tarifa_multa_dia', '500', 'number', 'Tarifa por cada día de atraso'),
('expiracion_reserva_horas', '48', 'number', 'Horas antes de que expire una reserva');

-- Triggers y Funciones
-- Actualizar stock al prestar
CREATE OR REPLACE FUNCTION handle_loan_checkout()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.books
    SET cantidad_disponible = cantidad_disponible - 1
    WHERE id = NEW.libro_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_loan_created
AFTER INSERT ON public.loans
FOR EACH ROW EXECUTE FUNCTION handle_loan_checkout();

-- Actualizar stock al devolver
CREATE OR REPLACE FUNCTION handle_loan_return()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'returned' AND OLD.estado != 'returned' THEN
        UPDATE public.books
        SET cantidad_disponible = cantidad_disponible + 1
        WHERE id = NEW.libro_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_loan_updated
AFTER UPDATE ON public.loans
FOR EACH ROW EXECUTE FUNCTION handle_loan_return();
